services:
  app:
    build: .
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
